import java.io.IOException;
import java.util.Objects;
import java.util.Scanner;

public class Main {
    public static TrainedModel training(Scanner scanner) {
        // === TRAINING DATA ===
        // A small labeled dataset — pairs of (sentence, label).
        // label = 1.0 means spam, 0.0 means not spam (ham).
        String[] sentences = {
                "buy cheap pills now",
                "meeting scheduled for tomorrow",
                "win a free prize today",
                "can we reschedule our call",
                "join our promotion telegram group",
                "please meet the deadline of the project",
                "enter our merch shop",
                "i've sent you the link for the site",
                "be part of our religion",
                "the meeting is going as planned"
        };
        float[] labels = {
                1f, 0f, 1f, 0f, 1f, 0f, 1f, 0f, 1f, 0f
        };

        // === BUILD THE VOCABULARY ===
        // Walk through every sentence, split into words, add each word to Vocabulary.
        String[][] words = new String[sentences.length][0];
        Vocabulary vocab = new Vocabulary();
        for (int i = 0; i < sentences.length; i++) {
            words[i] = sentences[i].trim().split("\\s+");
            for (int j = 0; j < words[i].length; j++) {
                vocab.addWord(words[i][j]);
            }
        }

        // === PRECOMPUTE INPUT VECTORS ===
        // Vectorize every sentence once, up front — since the vocabulary is now fixed,
        // re-vectorizing inside the epoch loop would just repeat identical work.
        float[][] trainingInputs = new float[sentences.length][];
        for (int i = 0; i < sentences.length; i++) {
            trainingInputs[i] = vocab.vectorize(words[i]);
        }

        // === CREATE THE NETWORK AND TRAINER ===
        Network network = new Network(vocab.size());
        Trainer trainer = new Trainer();
        float learningRate = 0.1f;
        int epochs = 500;

        // === TRAINING LOOP ===
        // Run through the entire dataset many times (epochs), calling trainOne
        // on each (sentence, label) pair every time.
        for (int i = 0; i < epochs; i++) {
            for (int j = 0; j < sentences.length; j++) {
                trainer.trainOne(network, trainingInputs[j], labels[j], learningRate);
            }
        }

        TrainedModel networkModel = new TrainedModel(vocab, network);

        System.out.printf("""
                
                Model trained sucessfully after %d epochs at %.2f learning rate!
                
                1 - Continue
                2 - Save network
                0 - Exit\n""", epochs, learningRate);
        int userInput1 = scanner.nextInt();
        scanner.nextLine();

        switch (userInput1) {
            case 1:
                break;
            case 2:
            {
                System.out.println("Insert the name of the model you are about to save: ");
                String name = scanner.nextLine();
                try {
                    TextPersistence.save(networkModel, name);
                }
                catch (IOException e) {
                    throw new RuntimeException(e);
                }
                break;
            }
        }

        return networkModel;
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("""
                
                1 - Start training
                2 - Load existing network
                0 - Exit""");
        int userInput1 = scanner.nextInt();
        scanner.nextLine();
        TrainedModel networkModel = null;
        switch (userInput1) {
            case 1:
                networkModel = training(scanner);
                break;
            case 2:
                System.out.println("\nInsert the EXACT name of the model you want to load: ");
                String name = scanner.nextLine();
                try {
                    networkModel = TextPersistence.load(name);
                }
                catch (IOException e) {
                    throw new RuntimeException(e);
                }
                break;
            case 0:
                System.exit(0);
                break;
            default:
                System.out.println("Input not recognized.");
                System.exit(0);
                break;
        }

        Network network = networkModel.getNetwork();
        Vocabulary vocab = networkModel.getVocabulary();

        // === TEST ON NEW SENTENCES ===
        // Run through sentences generated by the user to return a prediction
        while (true) {
            System.out.println("\nInsert a text sentence or type EXIT to close the program: ");
            String testSentence = scanner.nextLine();

            if (Objects.equals(testSentence, "EXIT")) {
                System.exit(0);
            }

            String[] testWords = testSentence.trim().split("\\s+");
            float[] resultVector = vocab.vectorize(testWords);
            System.out.printf("\n%s -> %.2f", testSentence, network.predict(resultVector));
        }
    }
}
